### ISSUE TITLE
CORS stop working after app restart in Azure web

### ISSUE THREAD

**Issue by SergeyRudakov** [aspnet/CORS#36] opened 2015-09-21 19:43 UTC
Maybe this is related to asp.net 5 core and not to cors middleware but I with `UseCors()` and `[EnableCors]` options used CORS is working fine only temporarily. On Azure (probably after app restart) cors policy settings disappear and I can't access service from other domain (No 'Access-Control-Allow-Origin' header is present on the requested resource).

Here is my configuration (UseCors is placed after UseMvc).
```
public void ConfigureServices(IServiceCollection services)
        {
            configureCors(services);
            services.AddMvc(options =>
            {
                options.Filters.Add(new ErrorFilter());
            });

        }


        private static void configureCors(IServiceCollection services)
        {
            services.AddCors();
           
            services.ConfigureCors(x => x.AddPolicy("allowAll", p=>p.AllowAnyOrigin().
            AllowAnyHeader().AllowAnyMethod().AllowCredentials()));
        }

        public void Configure(IApplicationBuilder app, IApplicationEnvironment env,  ILoggerFactory loggerFactory)
        {
            ConfigureOAuthTokenConsumption(app);
           
            app.UseMiddleware<StaticFileMiddleware>(new StaticFileOptions());
            app.UseErrorPage();

            app.UseMvc();
           
            app.UseCors("allowAll");

        }
```

*[UPDATE]*
Everything works fine when I removed UseCors() from the Startup.cs but kept the Attribute.
So when both options are in place we might have strange behavior when Cors works normally only in the beginning.

**Comment by Eilon** [comment] 2015-09-22 17:35
@kichalla can you take a look at this to see what the issue is?

**Comment by kichalla** [comment] 2015-09-23 19:56
@SergeyRudakov Which version of asp.net 5 are you using...beta7? also couple of things: 

- You need not use `app.UseCors("allowAll");` middleware here as its only supposed to be used when you are not using Mvc. 
- You need not call `services.AddCors()` here as `AddMvc` internally already does that.

**Comment by SergeyRudakov** [comment] 2015-09-23 21:37
I'm using beta7. And yeah, it works fine without services.AddCors(). So now I only have Cors policy configuration and [EnableCors("allowAll")] attribute added to the base controller.
Thank you,

I think we can close this issue, just wanted to let you know that in case everything is turned on it also works but only for a while.

**Comment by kichalla** [comment] 2015-09-24 00:08
Thanks for confirming. Closing the issue now.

**Closed by kichalla** 2015-09-24 00:08 UTC
Labels: investigate
