### ISSUE TITLE
CORS is not enabled when there is any error occured

### ISSUE THREAD

**Issue by TonyWoo** [aspnet/CORS#56] opened 2015-12-09 01:59 UTC
I enabled the CORS support using Microsoft.AspNet.Cors.Core(6.0.0-beta8) and Microsoft.AspNet.Cors (6.0.0-rc1-final) in a ASP.NET 5 RC1 project.

It is ok when the api called succeeded. 

But when I use JWT bearer middleware and provided a invalid token, the middleware throw an 500 error, then the CORS is not enabled, no Access-Control-Allow-Origin in the HTTP headers.  Can you help how to add the CORS when there is any error occurred? Thanks.

**Comment by andrevlins** [comment] 2015-12-10 18:21
I'm having the same issue with RC1

**Comment by Eilon** [comment] 2015-12-15 00:50
@kichalla any idea?

**Comment by kichalla** [comment] 2015-12-15 16:46
@TonyWoo @andrevlins  Can you share how your Startup's Configure method looks like?

Are you using Cors by doing `UseCors` (in which case you would be using Cors middleware) or not (in which case Mvc middleware itself has Cors support)?

**Comment by kichalla** [comment] 2015-12-21 17:59
@TonyWoo @andrevlins Closing this now. Feel free to re-open it if you still see an issue and also please provide some repro code.

**Closed by kichalla** 2015-12-21 17:59 UTC
Labels: investigate, wontfix

**Comment by andrevlins** [comment] 2015-12-21 19:24
My problem was solved using https://github.com/aspnet/CORS/issues/46 solution.

**Comment by kichalla** [comment] 2015-12-21 19:28
Good to know. Thanks!

**Comment by Icestorm0141** [comment] 2016-05-17 18:27
@kichalla So I'm definitely having this problem. I tried the proposed solution, implementing a CustomExceptionFilter which inherits from ExceptionFilterAttribute. The problem is that there isnt an Exception being thrown. Instead you're just failing the Authorization check. Any ideas? A couple of thoughts:

1) Does this just need to inherit from AuthorizationAttribute instead of ExceptionFilterAttribute and override some other method?
2) I stumbled across the [CorsAuthorizationFilter](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Cors/CorsAuthorizationFilter.cs) and am wondering if this should come into play here. Havent been able to find ANY documentation though on how to implement this.
3) I have what would probably be a working solution using the UseExceptionHandler middleware, but since I have not added the CORS headers, the actual response is moot. Here's that solution: 
`app.UseExceptionHandler(appBuilder =>
            {
                appBuilder.Use(async (context, next) =>
                {
                    var error = context.Features[typeof(IExceptionHandlerFeature)] as IExceptionHandlerFeature;
                    if (error != null && error.Error is SecurityTokenExpiredException)
                    {
                        context.Response.StatusCode = 401;
                        context.Response.ContentType = "application/json";
                        await context.Response.WriteAsync(
                            JsonConvert.SerializeObject(
                                new { authenticated = false, tokenExpired = true }));
                    }
                    else if (error != null && error.Error != null)
                    {
                        context.Response.StatusCode = 500;
                        context.Response.ContentType = "application/json";
                       // TODO: Shouldn't pass the exception message straight out, change this.
                        await context.Response.WriteAsync(
                            JsonConvert.SerializeObject
                                (new { success = false, error = error.Error.Message }));
                    }
                    else await next();
                });

            });`
Here's my whole Startup.cs file: 
`
        private readonly IApplicationEnvironment _appEnvironment;
        public IConfiguration Configuration { get; set; }
        private TokenAuthOptions AuthOptions { get; set; }

        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
            // Set up configuration sources.
            var builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true); ;

            builder.AddEnvironmentVariables();
            Configuration = builder.Build().ReloadOnChanged("appsettings.json");
        }


        // This method gets called by the runtime. Use this method to add services to the container
        public void ConfigureServices(IServiceCollection services)
        {
            var appUrls = Configuration.GetSection("AllowedApplicationUrls");
            AuthOptions = Configuration.Get<TokenAuthOptions>("TokenAuthOptions");

            var key = RSAKeyUtils.GetKeyParameters(_appEnvironment.ApplicationBasePath + "/signingkey.json");
            AuthOptions.SigningCredentials = new SigningCredentials(new RsaSecurityKey(key), SecurityAlgorithms.RsaSha256Signature);

            services.AddInstance(AuthOptions);
            services.AddAuthorization(auth =>
            {
                auth.AddPolicy("AdministratorOnly", new AuthorizationPolicyBuilder()
                    .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme‌​)
                    .RequireRole(SecurityRoles.PharosAdmin)
                    .RequireAuthenticatedUser().Build());
            });
            services.AddEntityFramework()
                    .AddSqlServer()
                    .AddDbContext<AppDbContext>(options =>
                         options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<AppDbContext>()
                .AddDefaultTokenProviders();


            services.AddCors(options =>
            {
                options.AddPolicy("AllowSpecificOrigin",
                    builder =>
                    {
                        builder.WithOrigins(appUrls.Value)
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .WithExposedHeaders("Content-Disposition");
                    });
            });
            
            services.AddTransient<ILicenseManager, LicenseManager>();
            services.AddTransient<IDbLicenseManager, DbLicenseManager>();
            services.AddMvc(config =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                config.Filters.Add(new AuthorizeFilter(policy));
                config.Filters.Add(new ExceptionHandlerFilterAttribute());
            });
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseIISPlatformHandler();
            app.UseExceptionHandler(appBuilder =>
            {
                appBuilder.Use(async (context, next) =>
                {
                    var error = context.Features[typeof(IExceptionHandlerFeature)] as IExceptionHandlerFeature;
                    if (error != null && error.Error is SecurityTokenExpiredException)
                    {
                        context.Response.StatusCode = 401;
                        context.Response.ContentType = "application/json";
                        await context.Response.WriteAsync(
                            JsonConvert.SerializeObject(
                                new { authenticated = false, tokenExpired = true }));
                    }
                    else if (error != null && error.Error != null)
                    {
                        context.Response.StatusCode = 500;
                        context.Response.ContentType = "application/json";
                       // TODO: Shouldn't pass the exception message straight out, change this.
                        await context.Response.WriteAsync(
                            JsonConvert.SerializeObject
                                (new { success = false, error = error.Error.Message }));
                    }
                    else await next();
                });

            });

            app.UseStaticFiles();

            app.UseCors("AllowSpecificOrigin");
            ConfigureJwtToken(app);
            app.UseIdentity();
            app.UseMvc();



        }
        public void ConfigureJwtToken(IApplicationBuilder app)
        {
            //var issuer = "http://localhost:65003/";
            //var audience = "099153c2625149bc8ecb3e85e03f0022";
            //var secret = TextEncodings.Base64Url.Decode("IxrAjDoa2FqElO7IhrSrUJELhUckePEPVpaePlS_Xaw");
            app.UseJwtBearerAuthentication(options =>
            {
                options.AutomaticAuthenticate = true;
                // Basic settings - signing key to validate with, audience and issuer.
                options.TokenValidationParameters.IssuerSigningKey = AuthOptions.SigningCredentials.Key;
                options.TokenValidationParameters.ValidAudience = AuthOptions.Audience;
                options.TokenValidationParameters.ValidIssuer = AuthOptions.Issuer;
                options.TokenValidationParameters.ValidateSignature = true;
                options.TokenValidationParameters.ValidateLifetime = true;
                options.TokenValidationParameters.ClockSkew = TimeSpan.FromMinutes(0);
            });

        }

        // Entry point for the application.
        public static void Main(string[] args) => WebApplication.Run<Startup>(args);`
